### ISSUE TITLE
Add linux support?

### ISSUE THREAD

**Issue by qianfan-Zhao** [spiriou/microADB#1]
I had test the master branch that adb push/pull can work fine, but adb shell doesn't work due to lack support.

Is there has a version that can support linux platform, or any plan?

**Comment by spiriou** [comment]
Hi @qianfan-Zhao yes shell support for linux should be available soon

**Comment by spiriou** [comment]
Hi @qianfan-Zhao adb shell implementation for linux is currently in PR https://github.com/spiriou/microADB/pull/2 under testing before merge. Your feedback could be useful.

**Comment by qianfan-Zhao** [comment]
It's greate that the microADB can support linux now. I had test this on my ubuntu desktop, adb wifi can work fine.

Any idea that move adb into usb serialport?

**Comment by spiriou** [comment]
adb client only supports TCP and USB (adb custom driver) so usb serialport is not a supported usecase from adb client perspective. You would need to use an ADB USB driver instead of usb serialport on your device, such as:
- https://android.googlesource.com/kernel/common/+/59c75bcf603f355ff34282422e8c3f2165b9d5f2/drivers/usb/gadget/f_adb.c
- https://github.com/apache/incubator-nuttx/blob/master/drivers/usbdev/adb.c

**Comment by qianfan-Zhao** [comment]
> adb client only supports TCP and USB (adb custom driver)

Now USB supported custom driver only and any plan to implement the usb functionfs version?
